
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PC
 */
public class Contabilidad extends javax.swing.JFrame {

    private Connection con = null;
    private Statement stmt = null;
    private JFrame inicio;

    public Contabilidad(Connection con, Statement st, JFrame i) {
        initComponents();
        this.con = con;
        this.stmt = st;
        this.inicio = i;
        setSize(420, 330);
        setTitle("CONTABILIDAD");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        v1 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sum = new javax.swing.JButton();
        res = new javax.swing.JButton();
        divi = new javax.swing.JButton();
        resulti = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CEDI = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NAMI = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel1.setText("CONTABILIDAD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));
        getContentPane().add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 30));
        getContentPane().add(v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("VALOR1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("VALOR2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        sum.setText("+");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        getContentPane().add(sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 60, 30));

        res.setText("-");
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        getContentPane().add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 50, 30));

        divi.setText("/");
        divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diviActionPerformed(evt);
            }
        });
        getContentPane().add(divi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 60, 30));

        resulti.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        resulti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(resulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 80, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("RESULTADO ==>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jButton1.setText("*");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 50, 30));

        CEDI.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(CEDI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asesoria.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 60, 70));

        NAMI.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(NAMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel6.setText("CONTADOR");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 70, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contable.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -190, 450, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed

        int valor1, valor2, valor3, resultado;
        valor1 = Integer.parseInt(v1.getText().trim());
        valor2 = Integer.parseInt(v2.getText().trim());
        resultado = valor1 + valor2;
        resulti.setText("" + resultado);

    }//GEN-LAST:event_sumActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed

        int valor1, valor2, valor3, resultado;
        valor1 = Integer.parseInt(v1.getText().trim());
        valor2 = Integer.parseInt(v2.getText().trim());
        resultado = (valor1 - valor2);
        resulti.setText("" + resultado);
    }//GEN-LAST:event_resActionPerformed

    private void diviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diviActionPerformed
        int valor1, valor2, valor3, resultado;
        valor1 = Integer.parseInt(v1.getText().trim());
        valor2 = Integer.parseInt(v2.getText().trim());
        resultado = (valor1 / valor2);
        resulti.setText("" + resultado);
    }//GEN-LAST:event_diviActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int valor1, valor2, valor3, resultado;
        valor1 = Integer.parseInt(v1.getText().trim());
        valor2 = Integer.parseInt(v2.getText().trim());
        resultado = (valor1 * valor2);
        resulti.setText("" + resultado);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void VISUAL(String cedula) {

        String nom = "", ape = "";
        String sql = "SELECT * FROM General_User_Adm WHERE cedula='" + cedula + "'";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                nom = rs.getString("Nombre");
                ape = rs.getString("Apellido");
                NAMI.setText(nom + " " + ape);
                CEDI.setText(cedula);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEDI;
    private javax.swing.JLabel NAMI;
    private javax.swing.JButton divi;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton res;
    private javax.swing.JLabel resulti;
    private javax.swing.JButton sum;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v2;
    // End of variables declaration//GEN-END:variables
}
