
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.transform.Result;

/**
 *
 * @author PC
 */
public class Historial extends javax.swing.JFrame {

 
    private Connection con = null;
    private Statement stmt = null;
    private JFrame inicio;
    DefaultTableModel modelo;
 
    
    public Historial(Connection con, Statement st, JFrame i) {
      
       initComponents();
        this.con = con;
        this.stmt = st;
        this.inicio = i;
        setTitle("Registro y Control");
        this.setLocationRelativeTo(null);
        String cabecera []={"Hora","Fecha","Sintoma 1", "Sintoma 2", "Sintoma3","N consultas","Nombre"};
        String datos[][]={};
        modelo = new DefaultTableModel(datos,cabecera);
        jTable1.setModel(modelo);
        String sql = "SELECT * FROM Historia WHERE Cedula='"+Ventana.cedulau+"'";
        
        try
        {
            String hora,fecha,s1,s2,s3,name,consultas;
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                consultas = rs.getString("idCaracteristica");
                name = rs.getString("Nombre");
                hora = rs.getString("Hora");
                fecha = rs.getString("fecha");
                s1 = rs.getString("Sintoma1");
                s2 = rs.getString("Sintoma2");
                s3 = rs.getString("Sintoma3");
                Object da[]={hora,fecha,s1,s2,s3,consultas,name};
                modelo.addRow(da);
            }
            jTable1.setModel(modelo);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/iconoSands.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jLabel3.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        jLabel1.setText("DIRECCION CONTROL Y CALIDAD");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrativo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tekton Pro Cond", 0, 14))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(710, 367));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(710, 367));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back-iloveimg-resized.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 610, 100));

        jLabel2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        jLabel2.setText("HISTORIAL DEL PACIENTE");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrativo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tekton Pro Cond", 0, 14))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 250, 60));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/like.jpg"))); // NOI18N
        jLabelFondo.setPreferredSize(new java.awt.Dimension(550, 445));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1030, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MainMenu previus = new MainMenu(con,stmt,this);
        previus.setVisible(true);
        this.setVisible(false);
        previus.VISUAL(Ventana.cedulau);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
