
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class MainMenu extends javax.swing.JFrame {

    private Connection con = null;
    private Statement stmt = null;
    private JFrame inicio;

    public MainMenu(Connection con, Statement st, JFrame i) {
        this.con = con;
        this.stmt = st;
        this.inicio = i;

        initComponents();
        setTitle("Menu Principal");
        setSize(600, 550);
        BLOCK.setVisible(false);
        atras.setVisible(false);
        gg.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/IconoSands.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nami = new javax.swing.JLabel();
        BLOCK = new javax.swing.JLabel();
        CEDI = new javax.swing.JLabel();
        gg = new javax.swing.JLabel();
        jee = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        pan.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        pan.setForeground(new java.awt.Color(153, 0, 153));
        pan.setText("WELCOME HEALTHAPP ");
        pan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bases de Datos Y POO2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tekton Pro Cond", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(pan);
        pan.setBounds(150, 20, 380, 90);

        Bienvenido.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        Bienvenido.setText("\"SALUD, BIENESTAR Y CUIDADO\"");
        Bienvenido.setToolTipText("");
        Bienvenido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Bienvenido);
        Bienvenido.setBounds(130, 330, 400, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asesoria.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 140, 80, 60);

        Nami.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        Nami.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nami);
        Nami.setBounds(160, 130, 230, 30);

        BLOCK.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        BLOCK.setText("BLOQUEADO INTENTE DE NUEVO");
        getContentPane().add(BLOCK);
        BLOCK.setBounds(140, 220, 400, 80);

        CEDI.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        CEDI.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CEDI);
        CEDI.setBounds(160, 170, 200, 30);

        gg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gg.png"))); // NOI18N
        getContentPane().add(gg);
        gg.setBounds(230, 290, 220, 180);

        jee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/315363.png"))); // NOI18N
        getContentPane().add(jee);
        jee.setBounds(400, 100, 150, 150);

        atras.setText("Salir");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras);
        atras.setBounds(30, 510, 100, 23);

        Consultar.setBackground(new java.awt.Color(0, 153, 255));
        Consultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Consultar.setForeground(new java.awt.Color(255, 255, 255));
        Consultar.setText("DIAGNOSTICO");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(Consultar);
        Consultar.setBounds(60, 420, 220, 60);

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("HISTORIA CLINICA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 420, 220, 60);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 500, 170, 31);

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modificar Datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(90, 210, 120, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Admin.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void BLOQUEAR() {
        Consultar.setVisible(false);
        jButton2.setVisible(false);
        jButton1.setVisible(false);
        Bienvenido.setVisible(false);
        pan.setVisible(false);
        BLOCK.setVisible(true);
        atras.setVisible(true);
        jLabel3.setVisible(false);
        gg.setVisible(true);
        jButton3.setVisible(false);
        jee.setVisible(false);

    }

    public void VISUAL(String cedula) {

        String nom = "", ape = "";
        String sql = "SELECT * FROM General_User_Adm WHERE cedula='" + cedula + "'";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                nom = rs.getString("Nombre");
                ape = rs.getString("Apellido");
                Nami.setText(nom + " " + ape);
                CEDI.setText(cedula);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        MainUsers consul = new MainUsers(con, stmt, this);
        consul.setVisible(true);
        this.setVisible(false);
        consul.VISUAL(CEDI.getText());

    }//GEN-LAST:event_ConsultarActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        System.exit(0);
    }//GEN-LAST:event_atrasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Registro re = new Registro(con, stmt, this);
        re.setVisible(true);
        re.Abrir(CEDI.getText());

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Historial hi = new Historial(con, stmt, this);
        this.setVisible(false);
        hi.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BLOCK;
    private javax.swing.JLabel Bienvenido;
    public javax.swing.JLabel CEDI;
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel Nami;
    private javax.swing.JButton atras;
    private javax.swing.JLabel gg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jee;
    private javax.swing.JLabel pan;
    // End of variables declaration//GEN-END:variables
}
