/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Registro extends javax.swing.JFrame {

    private Connection con = null;
    private Statement stmt = null;
    private JFrame inicio;

    public Registro(Connection con, Statement st, JFrame i) {

        initComponents();
        this.con = con;
        this.stmt = st;
        this.inicio = i;
        setSize(500,600);
        this.setLocationRelativeTo(null);
        type.setText("USUARIO");
        type.setEnabled(false);
        Carg.setText("NINGUNO");
        Carg.setEnabled(false);
        type.setVisible(false);
        Carg.setVisible(false);
        L1.setVisible(false);
        L2.setVisible(false);
        Modif.setVisible(false);
        b.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        GENERO = new javax.swing.JLabel();
        ced = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Apelli = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        Carg = new javax.swing.JTextField();
        Contra = new javax.swing.JTextField();
        Box = new javax.swing.JComboBox<>();
        Ge = new javax.swing.JComboBox<>();
        b = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Modif = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Javanese Text", 0, 24)); // NOI18N
        jLabel2.setText("REGISTRO DE USUARIOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 330, 70));

        jLabel3.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 50));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 50));

        jLabel5.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        jLabel5.setText("Apellido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 50));

        jLabel6.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        jLabel6.setText("Edad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 50));

        jLabel7.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        jLabel7.setText("Cedula");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 130, 50));

        jLabel9.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        jLabel9.setText("Antecedentes");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        L2.setText("Tipo");
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 60, 30));

        L1.setText("Cargo");
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        GENERO.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        GENERO.setText("Genero");
        getContentPane().add(GENERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, 30));

        ced.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        getContentPane().add(ced, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 250, 40));

        Age.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 250, 40));

        Apelli.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        getContentPane().add(Apelli, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 250, 40));

        Name.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 88, 250, 40));
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 250, 30));
        getContentPane().add(Carg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 250, 30));

        Contra.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        getContentPane().add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 250, 30));

        Box.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Diabetes", "HiperTension", "Cancer", "Nunguno" }));
        getContentPane().add(Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 250, -1));

        Ge.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        Ge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino" }));
        Ge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeActionPerformed(evt);
            }
        });
        getContentPane().add(Ge, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 250, 30));

        b.setText("Atras");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Resgistrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 140, 50));

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back-iloveimg-resized.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 60, 50));

        Modif.setBackground(new java.awt.Color(51, 153, 255));
        Modif.setForeground(new java.awt.Color(255, 255, 255));
        Modif.setText("MODIFICAR");
        Modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifActionPerformed(evt);
            }
        });
        getContentPane().add(Modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 170, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-medico-de-cruces_23-2147539025.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -100, 520, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Nombre, Apellido, Edad, Genero, Antecedentes, Cargo, tipo, Contraseña;
        int cedula;

        try {
            cedula = Integer.parseInt(ced.getText().trim());
            Nombre = Name.getText().trim();
            Apellido = Apelli.getText().trim();
            Edad = Age.getText().trim();
            Contraseña = Contra.getText().trim();
            tipo = type.getText().trim();
            Antecedentes = Box.getSelectedItem().toString();
            Genero = Ge.getSelectedItem().toString();
            Cargo = Carg.getText().trim();

            String sql = "INSERT INTO General_User_Adm(Cedula,Nombre,Apellido,Edad,Contraseña,Genero,Antecedentes,Cargo,Tipo) VAlUES (" + cedula + ",'" + Nombre + "','" + Apellido + "','" + Edad + "','" + Contraseña + "','" + Genero + "','" + Antecedentes + "','" + Cargo + "','" + tipo + "')";
            System.out.println("sql= " + sql);
            int x = this.stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Mensaje: Registro Exitoso " + x);
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    void habilitar(){
        b.setVisible(true);
        jButton2.setVisible(false);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ventana men = new Ventana();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeActionPerformed

    private void ModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifActionPerformed

        String Nombre, Apellido, Edad, Genero, Antecedentes, Cargo, tipo, Contraseña;
        int cedula;

        try {
            cedula = Integer.parseInt(ced.getText().trim());
            Nombre = Name.getText().trim();
            Apellido = Apelli.getText().trim();
            Edad = Age.getText().trim();
            Contraseña = Contra.getText().trim();
            tipo = type.getText().trim();
            Antecedentes = Box.getSelectedItem().toString();
            Genero = Ge.getSelectedItem().toString();
            Cargo = Carg.getText().trim();

            String sql = "UPDATE General_User_Adm SET Nombre ='" + Nombre + "',Apellido='" + Apellido + "',Edad='" + Edad + "',Contraseña='" + Contraseña + "',Antecedentes='" + Antecedentes + "',Genero='" + Genero + "'WHERE Cedula=" + cedula + "";
            System.out.println("sql= " + sql);
            int x = this.stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Mensaje: modificados " + x);

        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());

        }


    }//GEN-LAST:event_ModifActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
       
    }//GEN-LAST:event_bActionPerformed

    
    public void Abrir(String cedula) {

        String nom = "", ape = "", Eda = "", Gener = "", Antecedentes = "", Pass = "";
        String sql = "SELECT * FROM General_User_Adm WHERE cedula='" + cedula + "'";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                nom = rs.getString("Nombre");
                ape = rs.getString("Apellido");
                Eda = rs.getNString("Edad");
                Pass = rs.getNString("Contraseña");
                Gener = rs.getNString("Genero");
                Antecedentes = rs.getNString("Antecedentes");
                Name.setText(nom);
                Apelli.setText(ape);
                ced.setText(cedula);
                Age.setText(Eda);
                Contra.setText(Pass);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        ced.setEnabled(false);
        Modif.setVisible(true);
        jButton1.setVisible(false);
        jButton2.setVisible(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Apelli;
    private javax.swing.JComboBox<String> Box;
    private javax.swing.JTextField Carg;
    private javax.swing.JTextField Contra;
    private javax.swing.JLabel GENERO;
    private javax.swing.JComboBox<String> Ge;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JButton Modif;
    private javax.swing.JTextField Name;
    private javax.swing.JButton b;
    javax.swing.JTextField ced;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables

}
