
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class RegisterAdmin extends javax.swing.JFrame {

    private Connection con = null;
    private Statement stmt = null;
    private JFrame inicio;
    
   

     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/iconoSands.jpg"));
        return retValue;
    }

    public RegisterAdmin(Connection con, Statement st, JFrame i) {
        initComponents();
        this.con = con;
        this.stmt = st;
        this.inicio = i;
        this.setTitle("Registro usuarios");
        setSize(640,600);
        this.setLocationRelativeTo(null);
        
        Typo.setText("ADMINISTRADOR");
        Typo.setEnabled(false);
        Ante.setText("NINGUNO");
        Ante.setEnabled(false);
        Contra.setText("1234");
        Contra.setEnabled(false);
        modi.setVisible(false);
        
        
      /* type.setVisible(false);
        Car.setVisible(false);
        L1.setVisible(false);
        L2.setVisible(false);
*/
       
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        REGISTRAR = new javax.swing.JButton();
        ExitUsuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        Typo = new javax.swing.JTextField();
        Contra = new javax.swing.JTextField();
        modi = new javax.swing.JButton();
        Ge = new javax.swing.JComboBox<>();
        Car = new javax.swing.JComboBox<>();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        Ce = new javax.swing.JTextField();
        Na = new javax.swing.JTextField();
        Ap = new javax.swing.JTextField();
        Ag = new javax.swing.JTextField();
        Ante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Gener2 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel5.setText("Edad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 250, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel4.setText("Apellido");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 210, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel2.setText("Cedula");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 120, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 160, 120, 30);

        REGISTRAR.setBackground(new java.awt.Color(0, 0, 0));
        REGISTRAR.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        REGISTRAR.setForeground(new java.awt.Color(255, 102, 0));
        REGISTRAR.setText("REGISTRAR");
        REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRARActionPerformed(evt);
            }
        });
        getContentPane().add(REGISTRAR);
        REGISTRAR.setBounds(370, 530, 180, 40);

        ExitUsuario.setBackground(new java.awt.Color(153, 153, 153));
        ExitUsuario.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        ExitUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/circled-left.png"))); // NOI18N
        ExitUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(ExitUsuario);
        ExitUsuario.setBounds(30, 520, 70, 70);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel3.setText("Genero");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 290, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel10.setText("REGISTRO DE NUEVOS FUNCIONARIOS Y EMPLEADOS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 30, 450, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Soul_Eater_Skull_by_fauxonym7_1.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 20, 130, 90);

        jLabel9.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel9.setText("Cargo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 330, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel12.setText("Tipo");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 430, 140, 30);
        getContentPane().add(jSeparator11);
        jSeparator11.setBounds(50, 460, 520, 10);

        jLabel13.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel13.setText("Contraseña");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 380, 140, 30);

        Typo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Typo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypoActionPerformed(evt);
            }
        });
        getContentPane().add(Typo);
        Typo.setBounds(260, 430, 250, 30);
        getContentPane().add(Contra);
        Contra.setBounds(260, 380, 250, 30);

        modi.setBackground(new java.awt.Color(0, 0, 0));
        modi.setForeground(new java.awt.Color(255, 102, 0));
        modi.setText("MODIFICAR");
        modi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modiActionPerformed(evt);
            }
        });
        getContentPane().add(modi);
        modi.setBounds(230, 530, 120, 40);

        Ge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino" }));
        getContentPane().add(Ge);
        Ge.setBounds(260, 290, 250, 30);

        Car.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Administrador de la Base de Datos", "Atencion al Cliente", "Contabilidad", "Soporte Tecnico", "Capacitador" }));
        getContentPane().add(Car);
        Car.setBounds(260, 330, 250, 30);
        getContentPane().add(jSeparator12);
        jSeparator12.setBounds(50, 500, 510, 10);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(50, 420, 510, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(50, 200, 510, 20);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(50, 240, 510, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(50, 280, 510, 20);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(50, 150, 510, 20);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(50, 320, 510, 10);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(50, 370, 510, 10);

        Ce.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeActionPerformed(evt);
            }
        });
        getContentPane().add(Ce);
        Ce.setBounds(260, 120, 250, 30);

        Na.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Na);
        Na.setBounds(260, 160, 250, 30);

        Ap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApActionPerformed(evt);
            }
        });
        getContentPane().add(Ap);
        Ap.setBounds(260, 210, 250, 30);

        Ag.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgActionPerformed(evt);
            }
        });
        getContentPane().add(Ag);
        Ag.setBounds(260, 250, 250, 30);
        getContentPane().add(Ante);
        Ante.setBounds(260, 470, 250, 30);

        jLabel8.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel8.setText("Antecedentes");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 470, 210, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mask_001.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-200, 0, 1150, 640);

        jLabel11.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel11.setText("Genero");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 430, 140, 30);

        Gener2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Gener2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gener2ActionPerformed(evt);
            }
        });
        getContentPane().add(Gener2);
        Gener2.setBounds(260, 430, 260, 30);
        getContentPane().add(jSeparator10);
        jSeparator10.setBounds(50, 460, 510, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRARActionPerformed
      
      String Nombre, Apellido, Edad,Genero,Antecedentes,Cargo,tipo,Contraseña ;
        int cedula;

        try {
            cedula = Integer.parseInt(Ce.getText().trim());
            Nombre = Na.getText().trim();
            Apellido = Ap.getText().trim();
            Edad = Ag.getText().trim();
            Contraseña = Contra.getText().trim();
            tipo = Typo.getText().trim();
            Cargo = Car.getSelectedItem().toString();
            Genero = Ge.getSelectedItem().toString();
            Antecedentes = Ante.getText().trim();
           

            String sql = "INSERT INTO General_User_Adm(Cedula,Nombre,Apellido,Edad,Contraseña,Genero,Antecedentes,Cargo,Tipo) VAlUES (" + cedula + ",'" + Nombre + "','" + Apellido + "','" + Edad + "','" + Contraseña + "','" + Genero + "','" + Antecedentes + "','" + Cargo + "','" + tipo + "')";
            System.out.println("sql= " + sql);
            int x = this.stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Mensaje: Registro Exitoso" + x);
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_REGISTRARActionPerformed

    
    private void ExitUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitUsuarioActionPerformed
        Administrativo previus = new  Administrativo(con, stmt, this);
        previus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitUsuarioActionPerformed

  
    
     public void Cargardatos(String cedula) {

        String nom = "", ape = "", Eda = "", Gener = "", Antecedentes = "", Pass = "";
        String sql = "SELECT * FROM General_User_Adm WHERE cedula='" + cedula + "'";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                nom = rs.getString("Nombre");
                ape = rs.getString("Apellido");
                Eda = rs.getNString("Edad");
                Pass = rs.getNString("Contraseña");
                Gener = rs.getNString("Genero");
                Antecedentes = rs.getNString("Antecedentes");
                Na.setText(nom);
                Ap.setText(ape);
                Ce.setText(cedula);
                Ag.setText(Eda);
                Contra.setText(Pass);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void CeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CeActionPerformed

    private void ApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApActionPerformed

    private void AgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgActionPerformed

    private void Gener2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gener2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gener2ActionPerformed

    private void TypoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypoActionPerformed

    private void modiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modiActionPerformed
   
        String Nombre, Apellido, Edad, Genero, Antecedentes, Cargo, tipo, Contraseña;
        int cedula;

        try {
            cedula = Integer.parseInt(Ce.getText().trim());
            Nombre = Na.getText().trim();
            Apellido = Ap.getText().trim();
            Edad = Ag.getText().trim();
            Contraseña = Contra.getText().trim();
            Cargo = Car.getSelectedItem().toString();
            Genero = Ge.getSelectedItem().toString();


            String sql = "UPDATE General_User_Adm SET Nombre ='" + Nombre + "',Apellido='" + Apellido + "',Edad='" + Edad + "',Contraseña='" + Contraseña + "',Cargo='" + Cargo + "',Genero='" + Genero + "'WHERE Cedula=" + cedula + "";
            System.out.println("sql= " + sql);
            int x = this.stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Mensaje: modificados " + x);

        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());

        }


    }//GEN-LAST:event_modiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ag;
    private javax.swing.JTextField Ante;
    private javax.swing.JTextField Ap;
    private javax.swing.JComboBox<String> Car;
    private javax.swing.JTextField Ce;
    private javax.swing.JTextField Contra;
    private javax.swing.JButton ExitUsuario;
    private javax.swing.JComboBox<String> Ge;
    private javax.swing.JTextField Gener2;
    private javax.swing.JTextField Na;
    private javax.swing.JButton REGISTRAR;
    private javax.swing.JTextField Typo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton modi;
    // End of variables declaration//GEN-END:variables

}
