
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PC
 */
public class RegisMedics extends javax.swing.JFrame {

    private Connection con = null;
    private Statement stmt = null;
    private JFrame inicio;

    public RegisMedics(Connection con, Statement st, JFrame i) {

        initComponents();
        this.con = con;
        this.stmt = st;
        this.inicio = i;
        this.setTitle("Registro usuarios");
        setSize(450, 450);
        this.setLocationRelativeTo(null);
        contri.setText("1234");
        contri.setEnabled(false);
        Cuality.setText("MEDICO");
        Cuality.setVisible(false);
        modic.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Cedu = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Especi = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        contri = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Telf = new javax.swing.JTextField();
        Cuality = new javax.swing.JTextField();
        Gener = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        modic = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        b = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jLabel3.setText("jLabel3");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/purple-wallpaper-11.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRAR NUEVOS MEDICOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 20));
        getContentPane().add(Cedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, 30));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 30));
        getContentPane().add(Especi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 30));

        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, 30));
        getContentPane().add(contri, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 160, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 310, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 10));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 310, 0));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 310, 10));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 310, 20));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 310, 10));
        getContentPane().add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 310, 10));
        getContentPane().add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 300, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CEDULA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("NOMBRE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("ESPECIALIDAD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("EDAD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("GENERO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("CONTRASEÑA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("TELEFONO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 20));
        getContentPane().add(Telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 160, 30));
        getContentPane().add(Cuality, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, -1));

        Gener.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino" }));
        getContentPane().add(Gener, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 370, 110, 30));

        modic.setBackground(new java.awt.Color(0, 0, 0));
        modic.setForeground(new java.awt.Color(255, 153, 0));
        modic.setText("MODIFICAR");
        modic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modicActionPerformed(evt);
            }
        });
        getContentPane().add(modic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 120, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 20));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 20));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 20));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 20));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 20));
        getContentPane().add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 20));

        b.setText("Atras");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/purple-wallpaper-11.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -40, 700, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed
    
    void habilitar() {
        b.setVisible(true);
        modic.setVisible(true);
        jButton1.setVisible(false);
    }
    
    public void Cargardatos(String cedula) {

        String nom = "", ape = "", Eda = "", Gener = "", Pass = "", telefono="";
        String sql = "SELECT * FROM Medicos WHERE Cedula='" + cedula + "'";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                nom = rs.getString("Nombre");
                ape = rs.getString("Especialidad");
                Eda = rs.getNString("Edad");
                Pass = rs.getNString("Contraseña");
                Gener = rs.getNString("Genero");
                telefono = rs.getNString("Telefono");
                Name.setText(nom);
                Especi.setText(ape);
                Cedu.setText(cedula);
                Age.setText(Eda);
                contri.setText(Pass);
                Telf.setText(telefono);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String Nombre, Especialidad, Edad, Genero, Telefono, contraseña,cual;
        int Cedula;

        try {
            Cedula = Integer.parseInt(Cedu.getText().trim());
            Nombre = Name.getText().trim();
            Especialidad = Especi.getText().trim();
            Edad = Age.getText().trim();
            Genero = Gener.getSelectedItem().toString();
            contraseña = contri.getText().toString();
            Telefono = Telf.getText().trim();
             cual = Cuality.getText().trim();

            String sql = "INSERT INTO Medicos(Cedula,Nombre,Especialidad,Edad,Genero,Contraseña,Telefono,Cualidad) VAlUES (" + Cedula + ",'" + Nombre + "','" + Especialidad + "','" + Edad + "','" + Genero + "','" + contraseña + "','" + Telefono + "','" + cual + "')";
            System.out.println("sql= " + sql);
            int x = this.stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Mensaje: modificados " + x);
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
     Administrativo ad = new Administrativo(con,stmt,this);
     ad.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_bActionPerformed

    private void modicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modicActionPerformed
          
        String Nombre, Apellido, Edad, Genero, telefono, Especialista, tipo, Contraseña;
        int cedula;

        try {
            cedula = Integer.parseInt(Cedu.getText().trim());
            Nombre = Name.getText().trim();
            Especialista = Especi.getText().trim();
            Edad = Age.getText().trim();
            Contraseña = contri.getText().trim();
            Genero = Gener.getSelectedItem().toString();
            telefono = Telf.getText().trim();

            String sql = "UPDATE Medicos SET Nombre ='" + Nombre + "',Especialidad='" + Especialista + "',Edad='" + Edad + "',Contraseña='" + Contraseña + "',Telefono='" + telefono + "',Genero='" + Genero + "'WHERE Cedula=" + cedula + "";
            System.out.println("sql= " + sql);
            int x = this.stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Mensaje: modificados " + x);

        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());

        }


    }//GEN-LAST:event_modicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Cedu;
    private javax.swing.JTextField Cuality;
    private javax.swing.JTextField Especi;
    private javax.swing.JComboBox<String> Gener;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Telf;
    private javax.swing.JButton b;
    private javax.swing.JTextField contri;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton modic;
    // End of variables declaration//GEN-END:variables
}
